steps:
# Install dependencies
- name: 'python:3.11'
  entrypoint: pip
  args: ['install', '-r', 'requirements.txt', '-t', '.']

# Collect static files
- name: 'python:3.11'
  entrypoint: python
  args: ['manage.py', 'collectstatic', '--noinput']
  env:
    - 'DJANGO_SETTINGS_MODULE=core.settings'
    - 'DJANGO_DEBUG=False'
    - 'ALLOWED_HOSTS=.el.r.appspot.com'

# Deploy to App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['app', 'deploy', 'app.yaml']

timeout: '1600s' 